version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: medusa-server
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - ./backend:/app/medusa
      - backend_node_modules:/app/medusa/node_modules
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      SOLR_URL: http://solr:8983/solr/medusa
      JWT_SECRET: CHANGEME123
      COOKIE_SECRET: CHANGEME123
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: medusa-bucket
      MINIO_ACCESS_KEY: 7nR9aSt9LR32Py3o
      MINIO_SECRET_KEY: ath8oTjP2rLdhY08EwLMUZksvWwhPyGv
      ADMIN_CORS: http://medusa_admin:7000,http://localhost:7001,http://localhost:7000,http://localhost:7000
      STORE_CORS: http://localhost:3000,http://localhost:8000,http://storefront:8000
    
  postgres:
    image: postgres:10.4-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    
  redis:
    image: redis:7.0.7-alpine
    restart: always
    container_name: cache
    expose:
      - 6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_URL=redis://cache
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_BIND_ADDRESS=0.0.0.0
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9001:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
    
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin:latest
    restart: always
    depends_on:
      - backend
    container_name: medusa-admin
    ports:
      - "7700:7700"
    environment:
      MEDUSA_BACKEND_URL: http://backend:9000
      NODE_OPTIONS: --openssl-legacy-provider
    
  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    container_name: medusa-storefront
    restart: always
    depends_on:
      - backend
    volumes:
      - ./storefront:/app/storefront
      - storefront_node_modules:/app/storefront/node_modules
    ports:
      - "8100:8100"

volumes:
  storefront_node_modules:
  backend_node_modules:
  minio_data:
  postgres_data:
  redis_data:
